# Generated by Django 5.0 on 2025-12-26 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_options_alter_message_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 26, 6, 28, 40, 778553, tzinfo=datetime.timezone.utc)),
        ),
    ]
