# Generated by Django 5.0 on 2025-12-29 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 29, 6, 28, 22, 17612, tzinfo=datetime.timezone.utc)),
        ),
    ]
